const repo = {
    name: "LaunchX",
    author: "carlogilmar",
    language: "JavaScript",
    numberOfCommits: 100,
    stars: 199,
    forks: 299,
    issues_open: 10,
    issues_close: 10,
    getTotalIssues: function(){
      return this.issues_open + this.issues_close
    },
    getGeneralInfo: function(){
      return `This repository ${this.name} was created by ${this.author}`
    }
}
   
console.log("Nombre del repo:" + repo.name)
console.log("Issues totales: " + repo.getTotalIssues())
console.log(repo.getGeneralInfo())

const issue = {
  title: "Issue in review",
  repositoryNameAssociated: "Issues April 2022",
  status:"Review In process",
  numberOfComments: 5,
  labels: 1,
  author: "Marco Castro " ,
  dateCreated:"April 1st 2022",
  lastUpdated: "April 10 2022",
  getTitleAndAuthor: function(){
    return `The ${this.title} was generated by ${this.author}`
  },
  getGeneralInfo: function(){
    return `The issue was created at date: ${this.dateCreated} 
    and the last revision was at ${this.lastUpdated}. The status 
    of the issue is: ${this.status}.`
  }
}

console.log("subject: " + issue.repositoryNameAssociated)
console.log("Information: " + issue.getTitleAndAuthor())
console.log("Issue Information: " + issue.getGeneralInfo())

const pullRequest = {
  title: "Pull Request",
  branchName: "Second Branch",
  dateCreated:"April 1st 2022",
  status:"Review In process",
  repositoryNameAssociated: "Main Branch",
  getStatus: function(){
    return `The pull request was created at date: ${this.dateCreated} 
    and the status of the Pull Request is: ${this.status}.`
  },
  getTitleAndAuthor: function(){
    return `The ${this.title} was generated by ${this.author}`
  }
}

console.log("subject: " + pullRequest.status)
console.log("Information: " + issue.getTitleAndAuthor())

const twitter = {
  user: "Marco Heredia",
  username: "cykeeboy",
  age: 25,
  trendinTopic: "Activision",
  hashtag: "55% de mexicanos dispuesto a renunciar a su trabajo si no hay home office",
  getUserInfo: function(){
    return`The Twitter acount info is: User: ${this.user}, User Name: ${this.username} `
  },
  getTrendingAndHastag: function(){
    return`The Trending Topic is: ${this.trendinTopic}, And the Hashtag is: ${this.hashtag} `
  }
}

console.log(twitter.getUserInfo())
console.log(twitter.getTrendingAndHastag())
  
const facebook = {
  user: "facebook user",
  post: 22,
  biography: "Facebook daily user",
  getUserInfo: function(){
    return `This Facebook profile belongs to: ${this.user}, with ${this.post} posts.`
  },
  getUserBio: function(){
    return `The bio of the user is: ${this.biography}.`
  }
}
console.log(facebook.getUserInfo())
console.log(facebook.getUserBio())

const uber = {
  profile: "Uber User",
  travel: "CD MX, 10 km.",
  getTravelInfo: function(){
    return `The ${this.profile} requested a travel to ${this.travel}`
  }
}

console.log(uber.getTravelInfo())